# vim: set tabstop=2 shiftwidth=2 expandtab:

version: "3"
services:
  wasm:
    build:
      context: ./wasm
      dockerfile: Dockerfile
    # For `docker-compose build wasm --push`
    image: luke10x/webcurses:latest
    volumes:
      - ./wasm:/mnt/wasm:rw
      - ./src:/mnt/src:ro
      - ./include:/mnt/include:ro
    ports:
      - "${WASM_PORT:-9988}:8080"
    working_dir: /mnt/wasm
    entrypoint: "bash -c"
    command:
      - |
        echo Starting a web server in $(pwd) for web-curses
        python3 -mhttp.server 8080

    # node:
    #   image: node:16.19.0-buster-slim
    #   working_dir: /mnt/node
    #   volumes:
    #     - ./node:/mnt/node:rw
    #   entrypoint: "bash -c"
    #   command:
    #     - |
    #       npm run build
