# vim: set tabstop=2 shiftwidth=2 expandtab:

version: "3"
services:
  wasm:
    build:
      context: .
      dockerfile: wasm/Dockerfile
    # For `docker-compose build wasm --push`
    image: luke10x/webcurses:latest
    volumes:
      - ./wasm:/mnt/wasm:rw
      - ./terminal:/mnt/terminal:rw
      - ./examples:/mnt/examples:rw
      - ./include:/mnt/include:ro

    working_dir: /mnt/wasm
    
  website:
    image: nginx
    volumes:
      - ./website/index.html:/usr/share/nginx/html/index.html
      - ./website/favicon.ico:/usr/share/nginx/html/favicon.ico
      - ./terminal:/usr/share/nginx/html/terminal:ro
      - ./examples:/usr/share/nginx/html/examples:ro
      - ./wasm:/usr/share/nginx/html/wasm:ro
    ports:
      - "${WASM_PORT:-9988}:80"
